### ISSUE TITLE
Oppdatering av WP-plugin - validering av felter før lagring

### ISSUE THREAD

**Issue by supahleo** [digibib/bokanbefalinger#10]
Wordpress-pluginet oppdateres slik at anbefalingen ikke lagres dersom de obligatoriske feltene ikke er fylt inn (ISBN, teaser, målgruppe(r) for anbefalingen, anbefalers e-post, anbefalers navn).

Det vises en feilmelding til brukeren om hvilke felter som ikke er fyllt inn, men som må fylles inn for at anbefalingen skal bli lagret.

**Comment by boutros** [comment]
Har dere noen formening om hvordan denne feilmeldingen skal presenteres?

Slik som det er nå, så kommer feilbeskjedene øverst etter lagring (med rød skrift eller bakgrunn tror jeg). Men man får altså lagret og publisert anbefalingen på bloggen, selv om det er obligatoriske felter som ikke er fylt ut.

**Comment by supahleo** [comment]
Greit om vi følger beste praksis ved validering av skjemaer. Som vil tilsvare noe slik som merking av ledetekst og tekstfelt i rødt (slik det gjøres i skjemaet på anbefalinger.deichman.no) pluss en tydelig merket tekstbeskjed i nærheten av "Publiser"-knappen. 

Jeg lurer på om vi da kan erstatte de feilmeldingene som går på at "anbefalingen ble ikke pushet til...." med denne nye enkle feilmeldingen som de som skriver anbefalinger faktisk vil forstå?

**Comment by boutros** [comment]
OK. Må researche litt hvordan det kan løses. 
"Publiser"-knappen er i utganspunktet ikke noe pluginet har kontroll over, men det går vel an å hacke det til med å injisere noe javascript...

**Comment by supahleo** [comment]
Et relatert spørsmål: Hvordan får vi oppdatert pluginet hos de bloggene som har det installert?

Litterær puls går fint. Ellers er det Webløft og PvKrogh. Er det noen flere som bruker pluginet?

**Comment by boutros** [comment]
Idag så krever det manuell oppdatering. Dvs laste opp plugin på server selv.

For automatisk installasjon og oppdatering tror jeg pluginet må finnes i et eller annet offisielt wordpress plugin repository. Jeg vet ikke hva som skal til for å komme der, men det kan jeg undersøke.

**Comment by boutros** [comment]
Det ser ikke så omstendelig ut:
https://wordpress.org/plugins/about/

Ligger allerede 34279 plugins der allerede, så de kan ikke være særlig strenge.

**Comment by supahleo** [comment]
Inn i plugin repo hadde jo vært gøy. Men pri 1 nå er å utbedre det pluginet vi har for de få som bruker det. Manuell oppdatering av Litterær puls og Webløft er overkommelig.

**Comment by supahleo** [comment]
Benjamin har hatt en økt med Bokanbefalinger i dag. Denne issuen er neste på lista ift mine prioriteringer. Du har jo ferie Petter, men siden du har svart her nå i dag så er vi litt i stuss på om du planlegger å gjøre noe med denne saken?

Hvis nei; har du da noen tips fra toppen av hodet som kan gjøre denne jobben enklere for Benjamin?

**Comment by boutros** [comment]
Jeg kan se på det på søndag eller mandag

**Comment by boutros** [comment]
Har implementert validering på klientsiden.

Kan dere teste på litteraturbloggen og se om det er tilfredsstillende?

**Comment by supahleo** [comment]
Har testet og det ser bra ut for meg. Ber også Ingela om å teste.

Foreslår å gjøre teksten "Alle felter er obligatorisk" rød, samt å legge inn en rød stjerne bak alle ledetekstene også under "Metadata". Dette for gjøre det enda tydeligere for de som skriver anbefalinger.

**Comment by boutros** [comment]
Ok, det er gjort!
