### ISSUE TITLE
Feil i RSS-feed for søk på forfatter

### ISSUE THREAD

**Issue by asgeirr** [digibib/bokanbefalinger#11]
Søker på forfatter "Abo Rasul" og får tre anbefalinger:

http://anbefalinger.deichman.no/sok?forfatter=http%3A%2F%2Fdata.deichman.no%2Fperson%2Fx29672200

Kopierer RSS-feed, denne inneholder ikke anbefalinger av valgt forfatter, gir i stedet liste over nyeste anbefalinger, uavhengig av forfatter:

http://anbefalinger.deichman.no/feed?author=http%3A%2F%2Fdata.deichman.no%2Fperson%2Fx29672200

**Comment by bensinober** [comment]
Dette er sannsynligvis en feil bruk av APIet i genereringen av feed:

`http get anbefalinger.deichman.no/api/reviews author==http://data.deichman.no/person/x29672200`
vil ignorere author-parameteret
mens 

`http get anbefalinger.deichman.no/api/works author==http://data.deichman.no/person/x29672200 reviews==true`

vil gi anbefalinger på riktig forfatter.

dette er API-design, oppslag på verksdata (forfatter, boktittel, osv) må gå via `/api/works` mens oppslag på anbefalingdata (anbefaler, tittel, osv.) må gå via `/api/reviews`

**Comment by bensinober** [comment]
det skyldes at generering av lister utifra søk ikke hadde noe feed-alternativ for author og derfor defaulter til List.from_feed_url som i dette tilfellet er uten parametre years_from/to og pages og derfor defaulter til siste 10.
https://github.com/digibib/bokanbefalinger/blob/torquebox/routes/feed.rb#L13-26

**Comment by bensinober** [comment]
fikset med commit 76aa2a0c1a1951c270176c1c4df91cac6bf7e866
