### ISSUE TITLE
Bilder i RSS-strømmer

### ISSUE THREAD

**Issue by supahleo** [digibib/bokanbefalinger#4]
Ulike feilsituasjoner 
1) Omslagsbilder fra Bokkilden vises ikke, da vises default Bokanbefalinger-cover 
2) Omslagsbilder fra Bokkilden vises ikke i det hele tatt 
3) Noen ganger er størrelsen på bildet veldig stort. 

Vi må bistå PvKrogh i valg av RSS-plugin til Webløft Wordpressløsning. 

Vi kan sette opp en testblogg på blogg.deichman.no/anbefalingertest der vi kan teste de ulike temaene og RSS-pluginsene PvKrogh bruker i Webløft.

Eksempler:

http://anbefalinger.deichman.no/feed?languages=http%3A%2F%2Flexvo.org%2Fid%2Fiso639-3%2Fnno 

http://golbibliotek.no/?page_id=1905 

http://anbefalinger.deichman.no/feed?audience=http%3A%2F%2Fdata.deichman.no%2Faudience%2Fadult 

http://dbib.no/for-voksne/

**Comment by boutros** [comment]
Jeg har lagt til bilde i Atom feed, som `media:thumbnail`, det ser ut som det er det WP RSS import-pluginet vil ha.

Avventer tilbakemelding fra PvKrogh før jeg lukker denne

**Comment by boutros** [comment]
Lukker denne, fungerer på nye webløft-sidene:
http://test.webloft.no/?page_id=188
