### ISSUE TITLE
Høsting av nye omslagsbilder

### ISSUE THREAD

**Issue by supahleo** [digibib/bokanbefalinger#6]
En automatisert prosess som høster inn nye omslagsbilder fra Bokkilden og Krydderbasen (og evt andre kilder) med jevne mellomrom, feks månedlig.

Det gjøres bare spørring mot de titlene som ikke allerede har omslagsbilder.

Kjøre en spørring mot hele basen først, deretter redusere spørringene til å bare gjelde poster som er nye de siste 6 måneder.

**Comment by boutros** [comment]
Dette er nå håndtert, siden vi får oppdatering fra lsext triplestore nattlig
