### ISSUE TITLE
Endring av navn

### ISSUE THREAD

**Issue by supahleo** [digibib/bokanbefalinger#7]
Det er ikke mulig å endre navnet på anbefaler verken i http://anbefalinger.deichman.no/brukerstyring/  (for administrator) eller inne på http://anbefalinger.deichman.no/innstillinger (for brukeren selv)

**Comment by bensinober** [comment]
Dette er relatert til en bug i APIet (data.deichman.api).
En rekke mindre bugger er fikset og nye tester skrevet. 
Det er nå mulig å oppdatere navn og arbeidssted (=workplaceHomepage) på bruker  via APIet:

`PUT host:port/api/users api_key=apikey uri=http://uri.to/user name="New name"`
