### ISSUE TITLE
Anbefalinger fra Litteraturbloggen vises ikke på anbefalinger.deichman.no

### ISSUE THREAD

**Issue by supahleo** [digibib/bokanbefalinger#9]
![ba-feilmeld](https://cloud.githubusercontent.com/assets/117902/4914979/5b2f9d0e-64ca-11e4-84de-fbddedde83cb.png)
![ba-feilmeld2](https://cloud.githubusercontent.com/assets/117902/4914981/5ed32c14-64ca-11e4-96ae-7348f3935df6.png)

**Comment by bensinober** [comment]
I første søk i logger ser det ut som de som ikke er med aldri har kommet til APIet, så feilen må ligge i anbefalinger eller i nettforbindelsen

**Comment by bensinober** [comment]
Det viser seg at de gjeldende som ikke er med mangler felter som isbn, teaser, forfatter, o.l.
Endret bloggposten med tittel "Mitt liv med Agnes" til også å ha teaser, og da kom den med.

Mao. wordpresspluginet har en del obligatoriske felter som er merket av. De må fylles ut, men bør kanskje få beskjed hvis de ikke er fylt ut?

**Comment by boutros** [comment]
Man får beskjed dersom anbefalingen ikke har blitt pushet, og hvorfor:
https://github.com/digibib/wp-review-publish/blob/master/wp-review-publish.php#L164-L188

Men man blir ikke nektet å publisere bloggposten av den grunn. Skal vi ha en mer aggrisiv tilbakemedling? Popup?

**Comment by supahleo** [comment]
Jeg tror dessverre ikke at de som skriver anbefalinger bryr seg særlig om en slik feilmelding. Anbefalingen blir publisert på bloggen, ergo de antar ting er ok. Har laget en enhancement som forslag til løsning: https://github.com/digibib/bokanbefalinger/issues/10
